packages:
  - apps/*
  - examples/*
  - packages/*

catalog:
  '@effect/platform-bun': 4.0.0-beta.21
  '@effect/vitest': 4.0.0-beta.21
  effect: 4.0.0-beta.21

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@typescript/native-preview'
  - esbuild
  - msgpackr-extract
