name: Report an issue
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        This template is used for reporting an issue with Voidsync/Mimic.

        Before opening a new issue, please do a [search](https://github.com/voidhashcom/mimic/issues) of existing issues and :+1: upvote the existing issue instead. This will result in a quicker resolution.
  - type: textarea
    attributes:
      label: To Reproduce
      description: A step-by-step description of how to reproduce the issue, based on the linked reproduction. Screenshots can be provided in the issue body below. If using code blocks, make sure that [syntax highlighting is correct](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) and double check that the rendered preview is not broken.
      placeholder: |
        Ex:
        1. Create a new document with ...
        2. Apply operations ...
        3. X will happen
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current vs. Expected behavior
      description: |
        A clear and concise description of what the bug is (e.g., screenshots, logs, etc.), and what you expected to happen.

        **Skipping this/failure to provide complete information of the bug will result in the issue being closed.**
      placeholder: "Following the steps from the previous section, I expected A to happen, but I observed B instead."
    validations:
      required: true
  - type: input
    attributes:
      label: What version of @voidhash/mimic are you using?
      description: Please provide the current version of `@voidhash/mimic` or `@voidhash/mimic-effect` that you are reporting the bug on
      placeholder: "0.0.1-alpha.1"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Provide environment information
      description: Please collect the following information and paste the results.
      render: bash
      placeholder: |
        - OS: [e.g. macOS 14.6]
        - Runtime: [e.g. Bun 1.3.1]
        - Node version (if applicable): [e.g. Node.js 22.x]
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Which area(s) are affected? (Select all that apply)
      multiple: true
      options:
        - "@voidhash/mimic (core)"
        - "@voidhash/mimic-effect (server)"
        - "Documentation"
        - "Examples"
        - "Other"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Any extra information that might help us investigate. For example, is it only reproducible online, or locally too? Is the issue only happening in a specific browser? etc.
      placeholder: |
        I tested my reproduction against the latest release.
